# Vectors

In [1]:
import numpy as np

In [2]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [3]:
t[5]

28

In [14]:
print(np.where(t == min(t)))
print(np.where(t == max(t)))

(array([0], dtype=int64),)
(array([6, 7], dtype=int64),)


In [15]:
a = np.array([120,150,90])
b = np.array([130,130,130])
c = np.array([144,216,180])

print(a+b+c)

[394 496 400]


### Линейная комбинация векторов

In [16]:
100*a + 50*b + 10*c

array([19940, 23660, 17300])

Если при линейной комбинации векторов мы получаем 0 вектор, то такие вектора называются *линейно зависимыми*. При этом один из них (но необязательно любой) можно представить как их линейную комбинацию  
Если нулевой вектор получить не удалось - такие комбинации называются *линейно независимыми*

In [19]:
a = np.array([3,4,5,9])
b = np.array([1,5,3,6])
x = 200
y = 400

In [20]:
y*b - x*a

array([-200, 1200,  200,  600])