# Vectors

In [30]:
import numpy as np
import pandas as pd

In [2]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [3]:
t[5]

28

In [14]:
print(np.where(t == min(t)))
print(np.where(t == max(t)))

(array([0], dtype=int64),)
(array([6, 7], dtype=int64),)


In [15]:
a = np.array([120,150,90])
b = np.array([130,130,130])
c = np.array([144,216,180])

print(a+b+c)

[394 496 400]


### Линейная комбинация векторов

In [16]:
100*a + 50*b + 10*c

array([19940, 23660, 17300])

Если при линейной комбинации векторов мы получаем 0 вектор, то такие вектора называются *линейно зависимыми*. При этом один из них (но необязательно любой) можно представить как их линейную комбинацию  
Если нулевой вектор получить не удалось - такие комбинации называются *линейно независимыми*

In [19]:
a = np.array([3,4,5,9])
b = np.array([1,5,3,6])
x = 200
y = 400

In [20]:
y*b - x*a

array([-200, 1200,  200,  600])

### Произведения векторов

Всего есть 4 вида произведения векторов:  
1. Скалярное (результат - число)  
2. Векторное (результат - вектор)
3. Смешанное (результат - число)
4. Тензорное (результат - матрица)

#### Скалярное произведение

Скалярное произведение ортогональных векторов дает нулевой вектор (ортогональность - прямой угол между векторами)

Длина вектора вычисляется как корень квадратный из произведения вектора на самого себя

In [21]:
x = np.array([4,5,-1])
y = np.array([2,0,1])

np.dot(x,y)

7

In [23]:
x@y

7

In [25]:
# длина вектора
np.linalg.norm(x)

6.48074069840786

In [29]:
# нормировка
print(x / np.linalg.norm(x))
print(np.linalg.norm(x / np.linalg.norm(x)))

[ 0.6172134   0.77151675 -0.15430335]
0.9999999999999999


In [31]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [32]:
Hut_Paradise_DF.head()

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16

In [33]:
data = Hut_Paradise_DF.values

In [35]:
data[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [36]:
data[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [37]:
data[2,3]

10

In [38]:
data.shape

(9, 6)

In [40]:
data[:,1] - data[:, -1]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [41]:
data[:,0]*400

array([26000, 28000, 48000, 14000, 16000, 20000, 40000, 36000, 34000],
      dtype=int64)

In [42]:
s = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])

In [44]:
data[:,4]@s

1348

In [45]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [46]:
# являются ли эти 3 вектора попарно ортогональными?
print(u@v)
print(u@w)
print(v@w)

0
0
0


In [48]:
z = 2*v - 3*w

In [49]:
z@u

0

In [50]:
print(u / np.linalg.norm(u))
print(v / np.linalg.norm(v))
print(w / np.linalg.norm(w))

[0.8660254  0.         0.28867513 0.28867513 0.28867513]
[ 0.          0.33333333  0.          0.66666667 -0.66666667]
[ 0.21320072 -0.85280287 -0.21320072  0.         -0.42640143]
